M48
; DRILL file {KiCad (6.0.1)} date Sat Aug 20 09:02:23 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-20T09:02:23-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X4.0059Y-5.6841
X4.2028Y-5.6841
T2
X7.7984Y-5.2697
X7.7984Y-5.3878
T0
M30
